In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(x)

[['Semarang' 213 20000.0 2.0]
 ['Jogja' 202 18000.0 4.0]
 ['Solo' 207 18000.0 2.0]
 ['Kediri' 233 27000.0 2.0]
 ['Jepara' 200 nan 3.0]
 ['Semarang' 213 28000.0 3.0]
 ['Jogja' 202 22000.0 2.0]
 ['Solo' 207 32000.0 nan]
 ['Kediri' 233 12000.0 3.0]
 ['Jepara' 200 25000.0 3.0]]


In [ ]:
print(y)

['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

print(x)

[['Semarang' 213.0 20000.0 2.0]
 ['Jogja' 202.0 18000.0 4.0]
 ['Solo' 207.0 18000.0 2.0]
 ['Kediri' 233.0 27000.0 2.0]
 ['Jepara' 200.0 22444.444444444445 3.0]
 ['Semarang' 213.0 28000.0 3.0]
 ['Jogja' 202.0 22000.0 2.0]
 ['Solo' 207.0 32000.0 2.6666666666666665]
 ['Kediri' 233.0 12000.0 3.0]
 ['Jepara' 200.0 25000.0 3.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)


[[0.0 0.0 0.0 1.0 0.0 213.0 20000.0 2.0]
 [0.0 1.0 0.0 0.0 0.0 202.0 18000.0 4.0]
 [0.0 0.0 0.0 0.0 1.0 207.0 18000.0 2.0]
 [0.0 0.0 1.0 0.0 0.0 233.0 27000.0 2.0]
 [1.0 0.0 0.0 0.0 0.0 200.0 22444.444444444445 3.0]
 [0.0 0.0 0.0 1.0 0.0 213.0 28000.0 3.0]
 [0.0 1.0 0.0 0.0 0.0 202.0 22000.0 2.0]
 [0.0 0.0 0.0 0.0 1.0 207.0 32000.0 2.6666666666666665]
 [0.0 0.0 1.0 0.0 0.0 233.0 12000.0 3.0]
 [1.0 0.0 0.0 0.0 0.0 200.0 25000.0 3.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[1 0 1 0 1 0 1 0 1 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)


In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.1915918438457855 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057819 -0.0701316764163541]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.30453019390224867 -0.307866172742979]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830127 -0.9069571034860731]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225302]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.1915918438457855 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057819 -0.07013167641635412]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.30453019390224867 -0.307866172742979]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830127 -0.9069571034860731]
 [1.0 0.0 0.0 -0.44973664397484414 0.20564033932253017]]
